<!DOCTYPE html>
<html>
<head>
    <base href="/book/">
    <meta charset="utf-8">
    <title>Source code</title>
    <link rel="stylesheet" href="css/style.css">
    <script src="js/jquery.min.js"></script>
</head>
<body>
    <div class="sample-container"></div>

    <script src="js/three.min.js"></script>
    <script src="js/pdf.min.js"></script>

    <script type="text/javascript">
        window.PDFJS_LOCALE = {
            pdfJsWorker: 'js/pdf.worker.js',
            pdfJsCMapUrl: 'cmaps'
        };
    </script>
    <script src="js/flip-book.js"></script>

    <script type="text/javascript">
        let template = {
            "html": "templates\/default-book-view.html",
            "styles": ["css\/font-awesome.min.css","css\/short-black-book-view.css"],
            "script": "js\/default-book-view.js",
            "sounds": {"startFlip":"sounds\/start-flip.mp3","endFlip":"sounds\/end-flip.mp3"}
        };
        $('.sample-container').FlipBook({
            // pdf: 'http://192.168.31.5:8088/book/Leiner-Restaurant-Menuplan.pdf',
            pageCallback: function(n) {
                return {
                    type: 'html',
                    src: 'preview/'+(n+1)+'.html',
                    interactive: true
                };
            },
            pages: 2,
            template: template
        });
    </script>
</body>
</html>