<?php
$get_cid = $this->pagevar['get_cid'] ?: 'all';
$dataset_id = 11009;

$db = db();
// 获取产品数据分页列表
if (Request::isAjax()) {
    $data = [];
    $items = $db->select('item', '*', [['state', '=', 1], 'AND', ['type', '=', 1], 'AND', ['page_id', '=', $dataset_id]], 'sortby DESC, id DESC');
    foreach ($items as $item) {
        ItemModel::setItem($item);
        $image = ItemModel::getImage('m_');
        $params = ItemModel::getMore('params');
        $data[] = [
            'image' => $image,
            'title' => $item['title'],
            'diatemer' => $params['diatemer'],
            'height' => $params['height'],
            'length' => $params['length'],
            'width' => $params['width'],
            'mounting_type' => $params['mounting_type'],
            'spl' => $params['spl'],
            'rated_voltage' => $params['rated_voltage'],
        ];
    }
    exit(json_encode(['data'=>$data]));
}

// 组件配置
$ukid = 'lfxmwrlb';
$this->assign('ukid', $ukid);
$this->assign('setting', [
    'dataset.id' => $dataset_id,
    'dataset.table' => 'item',
    'ukid' => $ukid
]);

// 分类列表
$categorys = $db->select('item', '*', [['state', '=', 1], 'AND', ['type', '=', 2], 'AND', ['page_id', '=', $dataset_id]], 'sortby DESC, id DESC');

// 当前分类多层级别
$levels = [];
if (!empty($categorys) && $get_cid != 'all') {
    $levels = helper('db/getItemLevels', [$get_cid]);
}
?>
<section <?=$this->uikit->getSettingAttrs('component', ['style'=>'--bgc-lg:var(--mix-39)'])?>>
    <div <?=$this->uikit->getSettingAttrs('container', ['class'=>'container container-2xl'])?>>
        <style>
            @layer {
                [<?=$ukid?>] .table th {
                    padding: .25rem .5rem;
                }

                [<?=$ukid?>] .table td {
                    padding: .5rem;
                }

                [<?=$ukid?>] .table-border thead th {
                    border-bottom: 1px solid var(--mix-35);
                    font-size: 12px;
                    color: var(--secondary);
                }

                [<?=$ukid?>] .table tbody td {
                    vertical-align: middle;
                    font-size: 14px;
                }

                [<?=$ukid?>] .table-stripe tbody tr:nth-of-type(odd) {
                    background-color: var(--mix-39);
                }

                [<?=$ukid?>] .pagination {
                    --hover-color: var(--secondary) !important;
                    --active-color: var(--secondary-20) !important;
                    --active-bgcolor: var(--secondary) !important;
                }
            }
        </style>

        <div class="banner relative w-expand-screen bg-cover bg-norepeat bg-center h-25 h-35-lg w-full" style="--bgi:url(<?=$this->asset('data/file/product-banner.jpg', true)?>)">
            <div class="absolute" style="bottom:40%;left:7%;">
                <h2 class="f-13 mix-40">PRODUCT</h2>
                <h1 class="normal f-21 mix-40">产品中心</h1>
            </div>
        </div>

        <div class="grid relative z-10">
            <div class="col-span-12 col-span-3-lg hidden block-lg">
                <?php
                if ( $categorys ):
                    // 如果是详情页就使用上级页面别名
                    $page_alias = $get_id ? $join_alias : $page_alias;
                ?>
                    <div <?=$this->uikit->getSettingAttrs('category', $_setting_category['root'])?>>
                        <style>
                            @import 'assets/js/lib/metismenu/metismenu.css' layer(lib);
                            @import 'assets/js/lib/metismenu/vertical.css' layer(lib);
                            @layer {
                                [<?=$ukid?>] .sidebar-nav .metismenu {
                                    --hover-color: var(--mix);
                                    --active-color: var(--secondary)
                                }

                                [<?=$ukid?>] .sidebar-nav .metismenu > li > a {
                                    padding: 1.2rem 2rem;
                                }

                                [<?=$ukid?>] .sidebar-nav .metismenu > li > a:hover {
                                    padding-left: 2.2rem;
                                }

                                [<?=$ukid?>] .sidebar-nav .metismenu > li.mm-active > a {
                                    font-weight: bold;
                                }

                                [<?=$ukid?>] .sidebar-nav .metismenu .mm-active > a:before {
                                    width: 12px;
                                    height: 12px;
                                    left: 10px;
                                    border: 0.25rem solid var(--secondary);
                                }

                                [<?=$ukid?>] .sidebar-nav .metismenu > li > a:before {
                                    content: "";
                                    position: absolute;
                                    width: 10px;
                                    height: 10px;
                                    left: 12px;
                                    top: 50%;
                                    border: 0.25rem solid var(--mix-30);
                                    border-radius: 50%;
                                    transform: translateY(-50%);
                                    transition: all 0.35s;
                                }

                                [<?=$ukid?>] .sidebar-nav .metismenu > li:not(.mm-active) > a:hover:before {
                                    border: 0.25rem solid var(--mix-15);
                                    border-radius: 50%;
                                    transform: translateY(-50%);
                                }

                                [<?=$ukid?>] .sidebar-nav .metismenu > li > a:after {
                                    content: "";
                                    position: absolute;
                                    bottom: 0;
                                    left: 0;
                                    right: 0;
                                    height: 1px;
                                    background-color: var(--mix-32);
                                    transition: all 0.2s;
                                }

                                [<?=$ukid?>] .sidebar-nav .metismenu ul li a:hover {
                                    padding-left: 1.5rem;
                                    background-color: var(--mix-38);
                                }

                                [<?=$ukid?>] .sidebar-nav .metismenu ul li.mm-active a {
                                    background-color: var(--secondary);
                                    color: var(--secondary-20);
                                }
                            }
                        </style>
                        <div class="flex items-center justify-between bg-primary f-13 py-8 px-8 primary-20" style="margin-top:-4.48rem;">
                            <div>悦福科技产品分类</div>
                            <div>
                                <svg width="38" height="38" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M15 15m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0" /><path d="M18.5 18.5l2.5 2.5" /><path d="M4 6h16" /><path d="M4 12h4" /><path d="M4 18h4" /></svg>
                            </div>
                        </div>
                        <div class="category sidebar-nav">
                            <ul class="metismenu invisible list-none mb-0 f-8" data-id="<?=$this->pagevar['get_cid'] ?: $item['pid']?>">
                                <?php
                                $categorys = helper('arr/tree', [$categorys]);
                                $tree_menu_options = ['url' => $page_alias . '/category/{id}.html', 'arrow' => 'arrow', 'arrow_add_url' => true];
                                $tree_menu_html = '';
                                helper('arr/tree_menu', [$categorys, &$tree_menu_html, 0, 3, 0, $tree_menu_options]);
                                echo $tree_menu_html;
                                ?>
                            </ul>
                        </div>

                        <script>
                            require(['metismenu/metismenu'], function () {
                                const $component = $('[<?=$ukid?>]');
                                const $metismenu = $component.find('.metismenu');
                                const category_id = $metismenu.data('id');
                                const $category = $metismenu.find('[data-id="' + category_id + '"]')
                                const category_pid = $category.data('pid');

                                $metismenu.find('[data-id="' + category_pid + '"]').addClass('mm-active');
                                $category.addClass('mm-active');
                                $metismenu.metisMenu();
                                $metismenu.removeClass('invisible');
                            });
                        </script>
                    </div>
                <?php endif?>

            </div>
            <div class="col-span-12 col-span-9-lg">
                <div <?=$this->uikit->getSettingAttrs('dataview', ['class'=>'bg-mix-40 px-12-md py-15 mt-n23-lg', 'style'=>'--minh:60rem'])?>>

                    <div class="mb-12 pb-8 bb-1 b-mix-30">
                        <?php if ( count($levels) == 2 ): ?>
                            <h6 class="normal"><?=$levels[0]['title']?></h6>
                            <h2><?=$levels[1]['title']?></h2>
                        <?php elseif ( count($levels) == 1 ): ?>
                            <h2><?=$levels[0]['title']?></h2>
                        <?php else: ?>
                            <h2><?=$page_title?></h2>
                        <?php endif?>
                    </div>

                    <div class="flex flex-col gy-10 mb-15">
                        <?php
                        $menu_attrs = SITE["menu_attrs_pid_{$get_cid}"];
                        $menu_attrs = array_filter(json_decode2($menu_attrs),fn($o) => $o['state'] === 1);
                        foreach ($menu_attrs as $attr1):
                        ?>
                            <div class="flex gx-8">
                                <div class="primary bold nowrap"><?=$attr1['title']?>></div>
                                <div>
                                    <ul class="flex flex-wrap gx-8 gy-4">
                                        <?php foreach (array_filter($attr1['children'], fn($o) => $o['state'] === 1) as $attr2): ?>
                                            <li>
                                                <label class="flex gx-1 items-center lh-1">
                                                    <div>
                                                        <input type="checkbox" class="form-checkbox" value="<?="{$attr1['id']}:{$attr2['id']}"?>">
                                                    </div>
                                                    <div class="nowrap"><?=$attr2['title']?></div>
                                                </label>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <div class="scroll-x">
                        <div id="datatable"></div>
                        <script>
                            require(['lib/tabulator/tabulator', 'css!lib/tabulator/tabulator'], function(Tabulator) {
                                const tabulator = new Tabulator('#datatable', {
                                    pagination: true,
                                    paginationMode: 'remote',
                                    ajaxURL: location.href,
                                    ajaxConfig: 'POST',
                                    ajaxParams: { cid: '<?=$get_cid?>' },
                                    dataSendParams: {
                                        'page': 'pagenum',
                                        'size': 'perpage'
                                    },
                                    paginationSize: 10,
                                    paginationInitialPage: 1,
                                    paginationSizeSelector: [10, 20, 30, 40, 50],
                                    paginationCounter: 'rows',
                                    selectableRows: true,
                                    selectableRowsRangeMode: 'click',
                                    height: '100%',
                                    filterMode: 'remote',
                                    layout: 'fitColumns',
                                    addRowPos: 'top',
                                    rowHeader: {
                                        resizable: false,
                                        frozen: true,
                                        width: 45,
                                        hozAlign: 'center',
                                        formatter: 'rownum',
                                        editor: false,
                                        headerSort: false
                                    },
                                    columnDefaults: {
                                        resizable: false,
                                        headerSort: false
                                    },
                                    columns:[
                                        {title:"Name", field:"name"},
                                    ],
                                })
                            })
                        </script>
                        <table class="table table-border table-stripe table-hover">
                            <thead>
                            <tr>
                                <th>IMAGE .</th>
                                <th>PART NUMBER .</th>
                                <th>Φ</th>
                                <th>HEIGHT</th>
                                <th>LENGTH</th>
                                <th>WIDTH</th>
                                <th>MOUNTING TYPE</th>
                                <th>SPL [DB]</th>
                                <th>RATED VOLTAGE</th>
                            </tr>
                            </thead>
                            <tbody>

                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>