<?php
// http://192.168.31.5:8088/dev/uikit?isbuilder=0&isplacehold=1&theme=0&path=number/d2/26
$isplacehold = $_GET['isplacehold']; // 使用图片占位符填充组件
$path = $_GET['path'];

$info = file_get_contents("http://192.168.31.5:8087/dev/import-uikit-db?path=$path&isplacehold=$isplacehold");
$info = json_decode($info, true);

$setting = json_decode($info['setting'], true);
if ($setting) {
    $_GET['isdemo'] = true; // 动态组件开启演示数据填充组件
    $iswrite = true; // 开启每次刷新组件重新写入缓存
} else {
    $setting = [];
    $iswrite = false;
}
// 模拟组件拖到 PBuilder 的效果
if ($_GET['isbuilder']) {
//    $_GET['isbuilder'] = true;
    echo '<script>pagevar.isBuilder = true; $("body").addClass("_component_");</script>';
}

echo $this->uikit->getContent($path, ['setting' => $setting], $iswrite);

// 开启背景和前景色反转的主题
if ($_GET['theme'] == 1) {
    echo "<script>$(function() { $('body>[uk]').addClass('theme-invert'); });</script>";
}

//echo '<script src="http://192.168.31.5:8087/build/skeleton.js"></script>';
