<?php
$theme = json_decode($site['theme'], true);
$theme_screen = $theme['screen'];
?>
<!DOCTYPE html>
<html lang="<?=$theme['base']['lang']?>" class="-<?=str_replace('/', '-', $page['page_alias'] ?: 'index'); ?>">
    <head>
        <base href="<?=ROOT_URL?>">
        <meta charset="utf-8">
        <meta name="renderer" content="webkit">
        <meta name="force-rendering" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="ie=edge,chrome=1">
        <?php if (!$theme_screen):?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <meta name="applicable-device" content="pc,mobile">
        <?php elseif ($theme_screen == 'pc'):?>
        <meta name="applicable-device" content="pc">
        <?php elseif ($theme_screen == 'mobile'):?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <meta name="applicable-device" content="mobile">
        <?php endif;?>
        <title><?=$seo['title']?></title>
        <meta name="keywords" content="<?=$seo['keywords']?>">
        <meta name="description" content="<?=$seo['description']?>">

        <?php
        // 网站图标
        if ($site['favicon']) {
            echo '<link rel="icon" href="' . assets($site['favicon']) . '">';
        }
        // 应用图标
        if ($site['touchicon']) {
            echo '<link rel="apple-touch-icon" href="' . assets($site['touchicon']) . '">';
        }
        // 应用清单
        if ($site['manifest']) {
            echo '<link rel="manifest" href="' . assets('manifest.json') . '">';
        }
        // 样式文件
        echo '<link href="' . assets('assets/css/pagepan.css') . '" rel="stylesheet">';
		echo '<link href="' . assets('assets/css/theme.css') . '" rel="stylesheet">';
        echo '<link href="' . assets('assets/css/animate.css') . '" rel="stylesheet">';
        // 自定义字体
        $site_fonts_list = $site['fonts_list'];
        if ($site_fonts_list) {
            $site_fonts_list = json_decode($site_fonts_list, true);
            foreach ($site_fonts_list as $font) {
                $fontid = $font['id'];
                $site_fonts_css = "data/font/$fontid/$fontid.css";
                echo '<link href="' . $site_fonts_css . '" rel="preload" as="style" onload="this.rel=\'stylesheet\'">';
            }
        }
        // 图文样式
        if ($site['open_graphic_css'] && $pagevar['page_type'] == 'graphic') {
            echo '<link href="' . assets('data/css/graphic.min.css') . '" rel="stylesheet">';
        }
        // 全局样式
        if ($site['open_global_css']) {
            echo '<link href="' . assets('data/css/global.min.css') . '" rel="stylesheet">';
        }
        ?>
        <script>
            const pagevar = <?=json_encode2($pagevar)?>;
            const RUN_MODE = '<?=RUN_MODE?>';
        </script>
        <script src="<?=assets('assets/js/require.js')?>"></script>
        <script src="<?=assets('assets/js/config.js')?>"></script>
        <script src="<?=assets('assets/js/lib/jquery.js')?>"></script>
        <script src="<?=assets('assets/js/app/main.js')?>"></script>
    </head>
    <body <?=$page_body_attrs; ?>>
        <?php
        // 全局页头
        if ($site['open_header_php']) {
            include ROOT_PATH . 'data/php/header.inc';
        }

        // 页面内容
        echo $this->section('content');

        // 全局页脚
        if ($site['open_footer_php']) {
            include ROOT_PATH . 'data/php/footer.inc';
        }
        // 全局脚本
        if ($site['open_global_js']) {
            echo '<script src="' . assets('data/js/global.min.js') . '"></script>';
        }
        // 在线客服
        if ($site['service3_open'] == 1) {
            echo html_decode(base64_decode($site['service3_code']));
        }
        // 社交分享
        if ($site['share3_open'] == 1) {
            echo html_decode(base64_decode($site['share3_code']));
        }
        // 流量统计
        if ($site['stats3_open'] == 1) {
            echo html_decode(base64_decode($site['stats3_code']));
        }
        ?>
    </body>
</html>